GO := go
GOLANG_CI := github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.5.0
GOVULNCHECK := golang.org/x/vuln/cmd/govulncheck@latest

# Generate labels for all language runtimes
.PHONY: generate
generate: run fmt

.PHONY: test
test:
	go test -v -count 1 ./...

.PHONY: vulncheck
vulncheck: ## Check for vulnerabilities in dependencies
	$(GO) run $(GOVULNCHECK) ./...

.PHONY: lint
lint: fmt vulncheck ## Run linters on all go files
	$(GO) run $(GOLANG_CI) run -v

.PHONY: fmt
fmt: ## Formats all go files
	go tool gofumpt -l -w -extra  .
	find . -type f -name '*.go' -exec grep -L -E 'Code generated by .*\. DO NOT EDIT.' {} + | xargs go tool goimports -format-only -w -local=github.com/rudderlabs

.PHONY: run
run:
	go run cmd/generate/main.go
