# Generate labels for all language runtimes
.PHONY: generate
generate: run fmt

.PHONY: test
test:
	go test -v -count 1 ./...

.PHONY: lint
lint: fmt ## Run linters on all go files
	go tool golangci-lint run -v ./...


.PHONY: fmt
fmt: ## Formats all go files
	go tool gofumpt -l -w -extra  .
	find . -type f -name '*.go' -exec grep -L -E 'Code generated by .*\. DO NOT EDIT.' {} + | xargs go tool goimports -format-only -w -local=github.com/rudderlabs

.PHONY: run
run:
	go run cmd/generate/main.go