# Generate labels for all language runtimes
.PHONY: generate
generate: run fmt

.PHONY: test
test:
	go test -v -count 1 ./...

.PHONY: lint
lint: fmt ## Run linters on all go files
	golangci-lint run -v --timeout 5m

install-tools:
	go install mvdan.cc/gofumpt@latest
	go install gotest.tools/gotestsum@v1.10.0
	go install golang.org/x/tools/cmd/goimports@latest
	bash ./scripts/install-golangci-lint.sh v1.55.2

.PHONY: fmt
fmt: install-tools ## Formats all go files
	gofumpt -l -w -extra  .
	find . -type f -name '*.go' -exec grep -L -E 'Code generated by .*\. DO NOT EDIT.' {} + | xargs goimports -format-only -w -local=github.com/rudderlabs

.PHONY: run
run:
	go run cmd/generate/main.go